from building import *

cwd = GetCurrentDir()

src = Split('''
board.c
drv_clk.c
drv_common.c
drv_gpio.c
drv_usart.c
''')

CPPPATH = [cwd, cwd + '/include', cwd + '/include/config']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
