from building import *

cwd = GetCurrentDir()

src = Split('''
CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.S
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
''')

CPPPATH = [
    cwd + '/CMSIS/Device/ST/STM32F4xx/Include',
    cwd + '/CMSIS/Include',
    cwd + '/STM32F4xx_HAL_Driver/Inc',
    cwd + '/STM32F4xx_HAL_Driver/Inc/Legacy',
    Dir('#').abspath + '/drivers',
]

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
